version: "3.4"

services:
  web:
    container_name: dev-tools-web
    image: nginx
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8099:80"

  fpm:
    container_name: dev-tools-fpm
    image: darrenedale/equit:php-8.2-fpm
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: serverName=dev-tools-web-docker
    volumes:
      - ./:/app
      - ./docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - xdebug-client:host-gateway
