version: "3.4"

services:
  web:
    container_name: "dev-tools-web"
    depends_on:
      - "fpm"
    image: "nginx"
    working_dir: "/srv/dev-tools"
    volumes:
      - "./:/srv/dev-tools"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8099:80"

  fpm:
    container_name: "dev-tools-fpm"
    build:
      context: "./"
      dockerfile: "docker/fpm/Dockerfile"
    working_dir: "/srv/dev-tools"
    volumes:
      - "./:/srv/dev-tools"
    environment:
      PHP_IDE_CONFIG: "serverName=dev-tools-docker"

  cli:
    container_name: "dev-tools-cli"
    build:
      dockerfile: "./docker/cli/Dockerfile"
      context: "./"
    stdin_open: true
    tty: true
    volumes:
      - "./:/dev-tools"
    working_dir: "/dev-tools"
    extra_hosts:
      - "xdebug-client:host-gateway"
    environment:
      XDEBUG_SESSION: 1
      XDEBUG_CONFIG: "client_host=xdebug-client"
      PHP_IDE_CONFIG: "serverName=dev-tools-docker"
